### ISSUE TITLE
craftgr does not load on neoforge 20.6.61-beta

### ISSUE THREAD

**Issue by Manos654764** [KabanFriends/CraftGR#12]
CraftGR does not load because of a missing class.
provided is the crash log file:
https://mclo.gs/bjdLIWS

**Comment by KabanFriends** [comment]
Thank you for reporting, and sorry for late reply. I completely missed that they made a breaking change in NeoForge. (I'm still not very used to how NeoForge does things...)
I will fix this as soon as I can!
