### ISSUE TITLE
Cannot be used with Ad Astra.

### ISSUE THREAD

**Issue by infexpense** [KabanFriends/CraftGR#16]
Adastra-neoforge-1.20.4-1.16.5
Craft GR 1.6.1
I crashed before loading the mojang logo.

**Comment by KabanFriends** [comment]
That's a mod that I've never heard of. Can you send a crah report?

**Comment by infexpense** [comment]
> That's a mod that I've never heard of. Can you send a crah report?

==================== Basic Information ====================
FCL Version: 1.1.6.2
Architecture: arm64
Android SDK: 28
Java Version: 17
Renderer: Holy-GL4ES
Summarize: Application error, unable to launch, exit code = 1
==================== Basic Information ====================


invoke redirectStdio
invoke setLogPipeReady
[FCL Internal] /home/runner/work/FoldCraftLauncher/FoldCraftLauncher/FCLauncher/src/main/jni/fcl/fcl_loader.c:142
Log pipe ready.
invoke setFCLNativeWindow
invoke setEventPipe
[FCL Internal] /home/runner/work/FoldCraftLauncher/FoldCraftLauncher/FCLauncher/src/main/jni/fcl/fcl_bridge.c:60
setFCLNativeWindow : 0x6f2623a010, size : 2250x1080
[FCL Internal] /home/runner/work/FoldCraftLauncher/FoldCraftLauncher/FCLauncher/src/main/jni/fcl/fcl_event.c:193
Succeeded to set event pipe
==================== Start Minecraft ====================
Device: Honor Play
Architecture: arm64
CPU:kirin970
Android SDK: 28
==================== Env Map ====================
Env: PATH=/data/user/0/com.tungsten.fcl/app_runtime/java/jre17/bin:/sbin:/system/sbin:/system/bin:/system/xbin:/odm/bin:/vendor/bin:/vendor/xbin
Env: LIBGL_NOINTOVLHACK=1
Env: JAVA_HOME=/data/user/0/com.tungsten.fcl/app_runtime/java/jre17
Env: LIBGL_NAME=libgl4es_114.so
Env: LIBGL_STRING=Holy-GL4ES
Env: LIBGL_MIPMAP=3
Env: TMPDIR=/data/user/0/com.tungsten.fcl/cache
Env: LIBGL_ES=2
Env: LIBEGL_NAME=libEGL.so
Env: FCL_NATIVEDIR=/data/app/com.tungsten.fcl-oBjktDbIhxBmnVbnX1wD8A==/lib/arm64
Env: LIBGL_NOERROR=1
Env: LIBGL_VSYNC=1
Env: HOME=/storage/emulated/0/FCL/log
Env: LIBGL_NORMALIZE=1
==================== Env Map ====================
Working directory: /storage/emulated/0/FCL/.minecraft/versions/1.20.4
==================== Minecraft Arguments ====================
Java argument: /data/user/0/com.tungsten.fcl/app_runtime/java/jre17/bin/java
Java argument: -Djava.awt.headless=false
Java argument: -Dcacio.managed.screensize=2340x1080
Java argument: -Dcacio.font.fontmanager=sun.awt.X11FontManager
Java argument: -Dcacio.font.fontscaler=sun.font.FreetypeFontScaler
Java argument: -Dswing.defaultlaf=javax.swing.plaf.metal.MetalLookAndFeel
Java argument: -Dawt.toolkit=com.github.caciocavallosilano.cacio.ctc.CTCToolkit
Java argument: -Djava.awt.graphicsenv=com.github.caciocavallosilano.cacio.ctc.CTCGraphicsEnvironment
Java argument: -Djava.system.class.loader=com.github.caciocavallosilano.cacio.ctc.CTCPreloadClassLoader
Java argument: --add-exports=java.desktop/java.awt=ALL-UNNAMED
Java argument: --add-exports=java.desktop/java.awt.peer=ALL-UNNAMED
Java argument: --add-exports=java.desktop/sun.awt.image=ALL-UNNAMED
Java argument: --add-exports=java.desktop/sun.java2d=ALL-UNNAMED
Java argument: --add-exports=java.desktop/java.awt.dnd.peer=ALL-UNNAMED
Java argument: --add-exports=java.desktop/sun.awt=ALL-UNNAMED
Java argument: --add-exports=java.desktop/sun.awt.event=ALL-UNNAMED
Java argument: --add-exports=java.desktop/sun.awt.datatransfer=ALL-UNNAMED
Java argument: --add-exports=java.desktop/sun.font=ALL-UNNAMED
Java argument: --add-exports=java.base/sun.security.action=ALL-UNNAMED
Java argument: --add-opens=java.base/java.util=ALL-UNNAMED
Java argument: --add-opens=java.desktop/java.awt=ALL-UNNAMED
Java argument: --add-opens=java.desktop/sun.font=ALL-UNNAMED
Java argument: --add-opens=java.desktop/sun.java2d=ALL-UNNAMED
Java argument: --add-opens=java.base/java.lang.reflect=ALL-UNNAMED
Java argument: --add-opens=java.base/java.net=ALL-UNNAMED
Java argument: -Xbootclasspath/a:/data/user/0/com.tungsten.fcl/app_runtime/caciocavallo17/cacio-shared-1.18-SNAPSHOT.jar:/data/user/0/com.tungsten.fcl/app_runtime/caciocavallo17/cacio-tta-1.18-SNAPSHOT.jar
Java argument: -Xmx2482m
Java argument: -Dfile.encoding=UTF-8
Java argument: -Dsun.stdout.encoding=UTF-8
Java argument: -Dsun.stderr.encoding=UTF-8
Java argument: -Djava.rmi.server.useCodebaseOnly=true
Java argument: -Dcom.sun.jndi.rmi.object.trustURLCodebase=false
Java argument: -Dcom.sun.jndi.cosnaming.object.trustURLCodebase=false
Java argument: -Dlog4j2.formatMsgNoLookups=true
Java argument: -Dlog4j.configurationFile=/storage/emulated/0/FCL/.minecraft/versions/1.20.4/log4j2.xml
Java argument: -Dminecraft.client.jar=/storage/emulated/0/FCL/.minecraft/versions/1.20.4/1.20.4.jar
Java argument: -Dfml.ignoreInvalidMinecraftCertificates=true
Java argument: -Dfml.ignorePatchDiscrepancies=true
Java argument: -Dext.net.resolvPath=/data/user/0/com.tungsten.fcl/app_runtime/java/jre17/resolv.conf
Java argument: -Djava.io.tmpdir=/data/user/0/com.tungsten.fcl/cache/fclauncher
Java argument: -Dos.name=Linux
Java argument: -Dos.version=Android-9
Java argument: -Dorg.lwjgl.opengl.libname=libgl4es_114.so
Java argument: -Dfml.earlyprogresswindow=false
Java argument: -Dwindow.width=2340
Java argument: -Dwindow.height=1080
Java argument: -Duser.home=/storage/emulated/0/FCL/.minecraft
Java argument: -Duser.language=zh
Java argument: -Duser.timezone=Asia/Shanghai
Java argument: -Djna.boot.library.path=/data/app/com.tungsten.fcl-oBjktDbIhxBmnVbnX1wD8A==/lib/arm64
Java argument: -Dorg.lwjgl.vulkan.libname=libvulkan.so
Java argument: -Djava.library.path=/data/user/0/com.tungsten.fcl/app_runtime/java/jre17/lib:/data/user/0/com.tungsten.fcl/app_runtime/java/jre17/lib/jli:/data/user/0/com.tungsten.fcl/app_runtime/java/jre17/lib/server:/system/lib64:/vendor/lib64:/vendor/lib64/hw:/data/app/com.tungsten.fcl-oBjktDbIhxBmnVbnX1wD8A==/lib/arm64
Java argument: -Dio.netty.native.workdir=/data/user/0/com.tungsten.fcl/app_runtime/java/jre17/lib:/data/user/0/com.tungsten.fcl/app_runtime/java/jre17/lib/jli:/data/user/0/com.tungsten.fcl/app_runtime/java/jre17/lib/server:/system/lib64:/vendor/lib64:/vendor/lib64/hw:/data/app/com.tungsten.fcl-oBjktDbIhxBmnVbnX1wD8A==/lib/arm64
Java argument: -Dminecraft.launcher.brand=Fold Craft Launcher
Java argument: -Dminecraft.launcher.version=1.1.6.2
Java argument: -cp
Java argument: /data/user/0/com.tungsten.fcl/app_runtime/lwjgl/lwjgl.jar:/storage/emulated/0/FCL/.minecraft/libraries/net/neoforged/fancymodloader/earlydisplay/2.0.17/earlydisplay-2.0.17.jar:/storage/emulated/0/FCL/.minecraft/libraries/net/neoforged/fancymodloader/loader/2.0.17/loader-2.0.17.jar:/storage/emulated/0/FCL/.minecraft/libraries/net/neoforged/coremods/6.0.4/coremods-6.0.4.jar:/storage/emulated/0/FCL/.minecraft/libraries/net/neoforged/fancymodloader/spi/2.0.17/spi-2.0.17.jar:/storage/emulated/0/FCL/.minecraft/libraries/cpw/mods/modlauncher/10.0.9/modlauncher-10.0.9.jar:/storage/emulated/0/FCL/.minecraft/libraries/cpw/mods/securejarhandler/2.1.24/securejarhandler-2.1.24.jar:/storage/emulated/0/FCL/.minecraft/libraries/net/neoforged/accesstransformers/at-modlauncher/10.0.1/at-modlauncher-10.0.1.jar:/storage/emulated/0/FCL/.minecraft/libraries/net/neoforged/accesstransformers/10.0.1/accesstransformers-10.0.1.jar:/storage/emulated/0/FCL/.minecraft/libraries/org/openjdk/nashorn/nashorn-core/15.4/nashorn-core-15.4.jar:/storage/emulated/0/FCL/.minecraft/libraries/org/ow2/asm/asm-commons/9.5/asm-commons-9.5.jar:/storage/emulated/0/FCL/.minecraft/libraries/net/neoforged/mergetool/2.0.0/mergetool-2.0.0-api.jar:/storage/emulated/0/FCL/.minecraft/libraries/org/ow2/asm/asm-util/9.5/asm-util-9.5.jar:/storage/emulated/0/FCL/.minecraft/libraries/org/ow2/asm/asm-analysis/9.5/asm-analysis-9.5.jar:/storage/emulated/0/FCL/.minecraft/libraries/org/ow2/asm/asm-tree/9.5/asm-tree-9.5.jar:/storage/emulated/0/FCL/.minecraft/libraries/net/neoforged/bus/7.2.0/bus-7.2.0.jar:/storage/emulated/0/FCL/.minecraft/libraries/org/ow2/asm/asm/9.5/asm-9.5.jar:/storage/emulated/0/FCL/.minecraft/libraries/net/minecraftforge/unsafe/0.2.0/unsafe-0.2.0.jar:/storage/emulated/0/FCL/.minecraft/libraries/com/electronwill/night-config/toml/3.6.4/toml-3.6.4.jar:/storage/emulated/0/FCL/.minecraft/libraries/com/electronwill/night-config/core/3.6.4/core-3.6.4.jar:/storage/emulated/0/FCL/.minecraft/libraries/net/neoforged/JarJarSelector/0.4.0/JarJarSelector-0.4.0.jar:/storage/emulated/0/FCL/.minecraft/libraries/net/neoforged/JarJarMetadata/0.4.0/JarJarMetadata-0.4.0.jar:/storage/emulated/0/FCL/.minecraft/libraries/org/apache/maven/maven-artifact/3.8.5/maven-artifact-3.8.5.jar:/storage/emulated/0/FCL/.minecraft/libraries/net/jodah/typetools/0.6.3/typetools-0.6.3.jar:/storage/emulated/0/FCL/.minecraft/libraries/net/minecrell/terminalconsoleappender/1.2.0/terminalconsoleappender-1.2.0.jar:/storage/emulated/0/FCL/.minecraft/libraries/net/fabricmc/sponge-mixin/0.13.1+mixin.0.8.5/sponge-mixin-0.13.1+mixin.0.8.5.jar:/storage/emulated/0/FCL/.minecraft/libraries/org/apache/commons/commons-lang3/3.13.0/commons-lang3-3.13.0.jar:/storage/emulated/0/FCL/.minecraft/libraries/net/sf/jopt-simple/jopt-simple/5.0.4/jopt-simple-5.0.4.jar:/storage/emulated/0/FCL/.minecraft/libraries/commons-io/commons-io/2.13.0/commons-io-2.13.0.jar:/storage/emulated/0/FCL/.minecraft/libraries/org/apache/logging/log4j/log4j-core/2.19.0/log4j-core-2.19.0.jar:/storage/emulated/0/FCL/.minecraft/libraries/org/apache/logging/log4j/log4j-api/2.19.0/log4j-api-2.19.0.jar:/storage/emulated/0/FCL/.minecraft/libraries/com/google/guava/guava/32.1.2-jre/guava-32.1.2-jre.jar:/storage/emulated/0/FCL/.minecraft/libraries/com/google/code/gson/gson/2.10.1/gson-2.10.1.jar:/storage/emulated/0/FCL/.minecraft/libraries/com/mojang/logging/1.1.1/logging-1.1.1.jar:/storage/emulated/0/FCL/.minecraft/libraries/org/jetbrains/annotations/22.0.0/annotations-22.0.0.jar:/storage/emulated/0/FCL/.minecraft/libraries/org/slf4j/slf4j-api/2.0.9/slf4j-api-2.0.9.jar:/storage/emulated/0/FCL/.minecraft/libraries/org/antlr/antlr4-runtime/4.13.1/antlr4-runtime-4.13.1.jar:/storage/emulated/0/FCL/.minecraft/libraries/net/minecraftforge/srgutils/0.4.15/srgutils-0.4.15.jar:/storage/emulated/0/FCL/.minecraft/libraries/org/codehaus/plexus/plexus-utils/3.3.0/plexus-utils-3.3.0.jar:/storage/emulated/0/FCL/.minecraft/libraries/org/jline/jline-reader/3.12.1/jline-reader-3.12.1.jar:/storage/emulated/0/FCL/.minecraft/libraries/com/machinezoo/noexception/noexception/1.7.1/noexception-1.7.1.jar:/storage/emulated/0/FCL/.minecraft/libraries/com/google/guava/failureaccess/1.0.1/failureaccess-1.0.1.jar:/storage/emulated/0/FCL/.minecraft/libraries/com/google/guava/listenablefuture/9999.0-empty-to-avoid-conflict-with-guava/listenablefuture-9999.0-empty-to-avoid-conflict-with-guava.jar:/storage/emulated/0/FCL/.minecraft/libraries/com/google/code/findbugs/jsr305/3.0.2/jsr305-3.0.2.jar:/storage/emulated/0/FCL/.minecraft/libraries/org/checkerframework/checker-qual/3.12.0/checker-qual-3.12.0.jar:/storage/emulated/0/FCL/.minecraft/libraries/com/google/errorprone/error_prone_annotations/2.11.0/error_prone_annotations-2.11.0.jar:/storage/emulated/0/FCL/.minecraft/libraries/com/google/j2objc/j2objc-annotations/1.3/j2objc-annotations-1.3.jar:/storage/emulated/0/FCL/.minecraft/libraries/org/jline/jline-terminal/3.12.1/jline-terminal-3.12.1.jar:/storage/emulated/0/FCL/.minecraft/libraries/cpw/mods/bootstraplauncher/1.1.2/bootstraplauncher-1.1.2.jar:/storage/emulated/0/FCL/.minecraft/libraries/net/neoforged/JarJarFileSystems/0.4.0/JarJarFileSystems-0.4.0.jar:/storage/emulated/0/FCL/.minecraft/libraries/com/github/oshi/oshi-core/6.4.5/oshi-core-6.4.5.jar:/storage/emulated/0/FCL/.minecraft/libraries/com/ibm/icu/icu4j/73.2/icu4j-73.2.jar:/storage/emulated/0/FCL/.minecraft/libraries/com/mojang/authlib/6.0.52/authlib-6.0.52.jar:/storage/emulated/0/FCL/.minecraft/libraries/com/mojang/blocklist/1.0.10/blocklist-1.0.10.jar:/storage/emulated/0/FCL/.minecraft/libraries/com/mojang/brigadier/1.2.9/brigadier-1.2.9.jar:/storage/emulated/0/FCL/.minecraft/libraries/com/mojang/datafixerupper/6.0.8/datafixerupper-6.0.8.jar:/storage/emulated/0/FCL/.minecraft/libraries/com/mojang/patchy/2.2.10/patchy-2.2.10.jar:/storage/emulated/0/FCL/.minecraft/libraries/com/mojang/text2speech/1.17.9/text2speech-1.17.9.jar:/storage/emulated/0/FCL/.minecraft/libraries/commons-codec/commons-codec/1.16.0/commons-codec-1.16.0.jar:/storage/emulated/0/FCL/.minecraft/libraries/commons-logging/commons-logging/1.2/commons-logging-1.2.jar:/storage/emulated/0/FCL/.minecraft/libraries/io/netty/netty-buffer/4.1.97.Final/netty-buffer-4.1.97.Final.jar:/storage/emulated/0/FCL/.minecraft/libraries/io/netty/netty-codec/4.1.97.Final/netty-codec-4.1.97.Final.jar:/storage/emulated/0/FCL/.minecraft/libraries/io/netty/netty-common/4.1.97.Final/netty-common-4.1.97.Final.jar:/storage/emulated/0/FCL/.minecraft/libraries/io/netty/netty-handler/4.1.97.Final/netty-handler-4.1.97.Final.jar:/storage/emulated/0/FCL/.minecraft/libraries/io/netty/netty-resolver/4.1.97.Final/netty-resolver-4.1.97.Final.jar:/storage/emulated/0/FCL/.minecraft/libraries/io/netty/netty-transport-classes-epoll/4.1.97.Final/netty-transport-classes-epoll-4.1.97.Final.jar:/storage/emulated/0/FCL/.minecraft/libraries/io/netty/netty-transport-native-unix-common/4.1.97.Final/netty-transport-native-unix-common-4.1.97.Final.jar:/storage/emulated/0/FCL/.minecraft/libraries/io/netty/netty-transport/4.1.97.Final/netty-transport-4.1.97.Final.jar:/storage/emulated/0/FCL/.minecraft/libraries/it/unimi/dsi/fastutil/8.5.12/fastutil-8.5.12.jar:/storage/emulated/0/FCL/.minecraft/libraries/net/java/dev/jna/jna-platform/5.13.0/jna-platform-5.13.0.jar:/storage/emulated/0/FCL/.minecraft/libraries/net/java/dev/jna/jna/5.13.0/jna-5.13.0.jar:/storage/emulated/0/FCL/.minecraft/libraries/org/apache/commons/commons-compress/1.22/commons-compress-1.22.jar:/storage/emulated/0/FCL/.minecraft/libraries/org/apache/httpcomponents/httpclient/4.5.13/httpclient-4.5.13.jar:/storage/emulated/0/FCL/.minecraft/libraries/org/apache/httpcomponents/httpcore/4.4.16/httpcore-4.4.16.jar:/storage/emulated/0/FCL/.minecraft/libraries/org/apache/logging/log4j/log4j-slf4j2-impl/2.19.0/log4j-slf4j2-impl-2.19.0.jar:/storage/emulated/0/FCL/.minecraft/libraries/org/joml/joml/1.10.5/joml-1.10.5.jar:/data/user/0/com.tungsten.fcl/files/plugins/MioLaunchWrapper.jar:/storage/emulated/0/FCL/.minecraft/versions/1.20.4/1.20.4.jar
Java argument: -Djava.net.preferIPv6Addresses=system
Java argument: -DignoreList=securejarhandler-2.1.24.jar,asm-9.5.jar,asm-commons-9.5.jar,asm-tree-9.5.jar,asm-util-9.5.jar,asm-analysis-9.5.jar,bootstraplauncher-1.1.2.jar,JarJarFileSystems-0.4.0.jar,client-extra,neoforge-,1.20.4.jar,1.20.4.jar
Java argument: -DmergeModules=jna-5.10.0.jar,jna-platform-5.10.0.jar
Java argument: -Dfml.pluginLayerLibraries=
Java argument: -Dfml.gameLayerLibraries=
Java argument: -DlibraryDirectory=/storage/emulated/0/FCL/.minecraft/libraries
Java argument: -p
Java argument: /storage/emulated/0/FCL/.minecraft/libraries/cpw/mods/securejarhandler/2.1.24/securejarhandler-2.1.24.jar:/storage/emulated/0/FCL/.minecraft/libraries/org/ow2/asm/asm/9.5/asm-9.5.jar:/storage/emulated/0/FCL/.minecraft/libraries/org/ow2/asm/asm-commons/9.5/asm-commons-9.5.jar:/storage/emulated/0/FCL/.minecraft/libraries/org/ow2/asm/asm-tree/9.5/asm-tree-9.5.jar:/storage/emulated/0/FCL/.minecraft/libraries/org/ow2/asm/asm-util/9.5/asm-util-9.5.jar:/storage/emulated/0/FCL/.minecraft/libraries/org/ow2/asm/asm-analysis/9.5/asm-analysis-9.5.jar:/storage/emulated/0/FCL/.minecraft/libraries/cpw/mods/bootstraplauncher/1.1.2/bootstraplauncher-1.1.2.jar:/storage/emulated/0/FCL/.minecraft/libraries/net/neoforged/JarJarFileSystems/0.4.0/JarJarFileSystems-0.4.0.jar
Java argument: --add-modules
Java argument: ALL-MODULE-PATH
Java argument: --add-opens
Java argument: java.base/java.util.jar=cpw.mods.securejarhandler
Java argument: --add-opens
Java argument: java.base/java.lang.invoke=cpw.mods.securejarhandler
Java argument: --add-exports
Java argument: java.base/sun.security.util=cpw.mods.securejarhandler
Java argument: --add-exports
Java argument: jdk.naming.dns/com.sun.jndi.dns=java.naming
Java argument: --add-exports
Java argument: cpw.mods.bootstraplauncher/cpw.mods.bootstraplauncher=ALL-UNNAMED
MainClass: mio.Wrapper
MainClass: cpw.mods.bootstraplauncher.BootstrapLauncher
Minecraft argument: --username
Minecraft argument: infexpense
Minecraft argument: --version
Minecraft argument: 1.20.4
Minecraft argument: --gameDir
Minecraft argument: /storage/emulated/0/FCL/.minecraft/versions/1.20.4
Minecraft argument: --assetsDir
Minecraft argument: /storage/emulated/0/FCL/.minecraft/assets
Minecraft argument: --assetIndex
Minecraft argument: 12
Minecraft argument: --uuid
Minecraft argument: 5dc5514a2b444e69aff4d614dde4928e
Minecraft argument: --accessToken
Minecraft argument: ***
Minecraft argument: --clientId
Minecraft argument: ${clientid}
Minecraft argument: --xuid
Minecraft argument: ${auth_xuid}
Minecraft argument: --userType
Minecraft argument: mojang
Minecraft argument: --versionType
Minecraft argument: Fold Craft Launcher
Minecraft argument: --width
Minecraft argument: 2340
Minecraft argument: --height
Minecraft argument: 1080
Minecraft argument: --fml.neoForgeVersion
Minecraft argument: 20.4.237
Minecraft argument: --fml.fmlVersion
Minecraft argument: 2.0.17
Minecraft argument: --fml.mcVersion
Minecraft argument: 1.20.4
Minecraft argument: --fml.neoFormVersion
Minecraft argument: 20231207.154220
Minecraft argument: --launchTarget
Minecraft argument: forgeclient
Hook exit success
[20:38:27] [main/INFO]: ModLauncher running: args [--username, infexpense, --version, 1.20.4, --gameDir, /storage/emulated/0/FCL/.minecraft/versions/1.20.4, --assetsDir, /storage/emulated/0/FCL/.minecraft/assets, --assetIndex, 12, --uuid, 5dc5514a2b444e69aff4d614dde4928e, --accessToken, ❄❄❄❄❄❄❄❄, --clientId, ${clientid}, --xuid, ${auth_xuid}, --userType, mojang, --versionType, Fold Craft Launcher, --width, 2340, --height, 1080, --fml.neoForgeVersion, 20.4.237, --fml.fmlVersion, 2.0.17, --fml.mcVersion, 1.20.4, --fml.neoFormVersion, 20231207.154220, --launchTarget, forgeclient]
[20:38:27] [main/INFO]: ModLauncher 10.0.9+10.0.9+main.dcd20f30 starting: java version 17.0.10-internal by N/A; OS Linux arch aarch64 version Android-9
[20:38:28] [main/INFO]: Loading ImmediateWindowProvider fmlearlywindow
[FCL Internal] /home/runner/work/FoldCraftLauncher/FoldCraftLauncher/FCLauncher/src/main/jni/lwjgl/fcl_hook.c:70
Registered forkAndExec
[20:38:28] [main/INFO]: Trying GL version 4.6
Initialising gl4es
v1.1.5 built on Sep 27 2023 17:42:09
Using GLES 2.0 backend
loaded: libGLESv2.so
loaded: libEGL.so
Using GLES 2.0 backend
Hardware Full NPOT detected and used
Extension GL_EXT_blend_minmax  detected and used
FBO are in core, and so used
PointSprite are in core, and so used
CubeMap are in core, and so used
BlendColor is in core, and so used
Blend Subtract is in core, and so used
Blend Function and Equation Separation is in core, and so used
Texture Mirrored Repeat is in core, and so used
Extension GL_OES_mapbuffer  detected
Extension GL_OES_element_index_uint  detected and used
Extension GL_OES_packed_depth_stencil  detected and used
Extension GL_OES_depth24  detected and used
Extension GL_OES_rgb8_rgba8  detected and used
Extension GL_EXT_texture_format_BGRA8888  detected and used
Extension GL_OES_depth_texture  detected and used
Extension GL_OES_texture_stencil8  detected and used
Extension GL_EXT_texture_rg  detected and used
Extension GL_EXT_color_buffer_float  detected and used
Extension GL_EXT_color_buffer_half_float  detected and used
high precision float in fragment shader available and used
Max vertex attrib: 16
Extension GL_OES_standard_derivatives  detected and used
Extension GL_ARM_shader_framebuffer_fetch detected and used
Extension GL_OES_get_program_binary  detected and used
Number of supported Program Binary Format: 1
Max texture size: 8192
Max Varying Vector: 15
Texture Units: 16/16 (hardware: 16), Max lights: 8, Max planes: 6
Hardware vendor is ARM
GLSL 300 es supported
GLSL 310 es supported and used
GLSL 320 es supported
Max Color Attachments: 4 / Draw buffers: 4
sRGB surface supported
EGLImage to Texture2D supported
EGLImage to RenderBuffer supported
ignore MipMap
glGetError() always return GL_NOERROR
Targeting OpenGL 2.1
No hack in shader converter to define overloaded function with int
Not trying to batch small subsequent glDrawXXXX
try to use VBO
glXMakeCurrent FBO workaround enabled
FBO workaround for using binded texture enabled
Force texture for Attachment color0 on FBO
Hack to trigger a SwapBuffers when a Full Framebuffer Blit on default FBO is done
Force normals to be normalized on FPE shaders
glX Will try to recycle EGL Surface
Current folder is:/storage/emulated/0/FCL/.minecraft/versions/1.20.4
[20:38:28] [main/INFO]: Requested GL version 4.6 got version 3.2
[20:38:29] [main/INFO]: SpongePowered MIXIN Subsystem Version=0.8.5 Source=union:/storage/emulated/0/FCL/.minecraft/libraries/net/fabricmc/sponge-mixin/0.13.1+mixin.0.8.5/sponge-mixin-0.13.1+mixin.0.8.5.jar%2388!/ Service=ModLauncher Env=CLIENT
[20:38:29] [pool-2-thread-1/INFO]: GL info: Mali-G72 GL version 2.1 gl4es wrapper 1.1.5, PojavLauncherTeam & ptitSeb
[20:38:30] [main/INFO]: Found mod file "adastra-neoforge-1.20.4-1.16.5.jar" of type MOD with provider {mods folder locator at /storage/emulated/0/FCL/.minecraft/versions/1.20.4/mods}
[20:38:30] [main/INFO]: Found mod file "botarium-neoforge-1.20.4-3.2.2.jar" of type MOD with provider {mods folder locator at /storage/emulated/0/FCL/.minecraft/versions/1.20.4/mods}
[20:38:30] [main/INFO]: Found mod file "craftgr-1.6.1-mc1.20.4.jar" of type MOD with provider {mods folder locator at /storage/emulated/0/FCL/.minecraft/versions/1.20.4/mods}
[20:38:30] [main/INFO]: Found mod file "resourcefulconfig-neoforge-1.20.4-2.4.7.jar" of type MOD with provider {mods folder locator at /storage/emulated/0/FCL/.minecraft/versions/1.20.4/mods}
[20:38:30] [main/INFO]: Found mod file "resourcefullib-neoforge-1.20.4-2.4.10.jar" of type MOD with provider {mods folder locator at /storage/emulated/0/FCL/.minecraft/versions/1.20.4/mods}
[20:38:30] [main/INFO]: Found mod file "YetAnotherConfigLib-3.5.0+1.20.4-neoforge.jar" of type MOD with provider {mods folder locator at /storage/emulated/0/FCL/.minecraft/versions/1.20.4/mods}
[20:38:31] [main/INFO]: Found mod file "client-1.20.4-20231207.154220-srg.jar" of type MOD with provider net.neoforged.fml.loading.moddiscovery.MinecraftLocator@a7f0ab6
[20:38:31] [main/INFO]: Found mod file "neoforge-20.4.237-universal.jar" of type MOD with provider net.neoforged.fml.loading.moddiscovery.MinecraftLocator@a7f0ab6
[20:38:32] [main/INFO]: Found 12 dependencies adding them to mods collection
[20:38:32] [main/INFO]: Found mod file "common-io-3.10.0.jar" of type GAMELIBRARY with provider net.neoforged.fml.loading.moddiscovery.JarInJarDependencyLocator@5fc930f0
[20:38:32] [main/INFO]: Found mod file "imageio-metadata-3.10.0.jar" of type GAMELIBRARY with provider net.neoforged.fml.loading.moddiscovery.JarInJarDependencyLocator@5fc930f0
[20:38:32] [main/INFO]: Found mod file "gson-0.2.1.jar" of type GAMELIBRARY with provider net.neoforged.fml.loading.moddiscovery.JarInJarDependencyLocator@5fc930f0
[20:38:32] [main/INFO]: Found mod file "bytecodecs-1.0.2.jar" of type GAMELIBRARY with provider net.neoforged.fml.loading.moddiscovery.JarInJarDependencyLocator@5fc930f0
[20:38:32] [main/INFO]: Found mod file "common-image-3.10.0.jar" of type GAMELIBRARY with provider net.neoforged.fml.loading.moddiscovery.JarInJarDependencyLocator@5fc930f0
[20:38:32] [main/INFO]: Found mod file "common-lang-3.10.0.jar" of type GAMELIBRARY with provider net.neoforged.fml.loading.moddiscovery.JarInJarDependencyLocator@5fc930f0
[20:38:32] [main/INFO]: Found mod file "jlayer-1.0.1.jar" of type GAMELIBRARY with provider net.neoforged.fml.loading.moddiscovery.JarInJarDependencyLocator@5fc930f0
[20:38:32] [main/INFO]: Found mod file "yabn-1.0.3.jar" of type GAMELIBRARY with provider net.neoforged.fml.loading.moddiscovery.JarInJarDependencyLocator@5fc930f0
[20:38:32] [main/INFO]: Found mod file "imageio-core-3.10.0.jar" of type GAMELIBRARY with provider net.neoforged.fml.loading.moddiscovery.JarInJarDependencyLocator@5fc930f0
[20:38:32] [main/INFO]: Found mod file "imageio-webp-3.10.0.jar" of type GAMELIBRARY with provider net.neoforged.fml.loading.moddiscovery.JarInJarDependencyLocator@5fc930f0
[20:38:32] [main/INFO]: Found mod file "mixinextras-neoforge-0.3.5.jar" of type GAMELIBRARY with provider net.neoforged.fml.loading.moddiscovery.JarInJarDependencyLocator@5fc930f0
[20:38:32] [main/INFO]: Found mod file "json-0.2.1.jar" of type GAMELIBRARY with provider net.neoforged.fml.loading.moddiscovery.JarInJarDependencyLocator@5fc930f0
java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at mio.Wrapper.main(Wrapper.java:21)
Caused by: java.lang.module.ResolutionException: Modules craftgr and jlayer export package javazoom.jl.player to module mixinextras.neoforge
	at java.base/java.lang.module.Resolver.resolveFail(Unknown Source)
	at java.base/java.lang.module.Resolver.failTwoSuppliers(Unknown Source)
	at java.base/java.lang.module.Resolver.checkExportSuppliers(Unknown Source)
	at java.base/java.lang.module.Resolver.finish(Unknown Source)
	at java.base/java.lang.module.Configuration.<init>(Unknown Source)
	at java.base/java.lang.module.Configuration.resolveAndBind(Unknown Source)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.ModuleLayerHandler.buildLayer(ModuleLayerHandler.java:75)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.TransformationServicesHandler.buildTransformingClassLoader(TransformationServicesHandler.java:60)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.Launcher.run(Launcher.java:106)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.Launcher.main(Launcher.java:78)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23)
	at cpw.mods.bootstraplauncher@1.1.2/cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:141)
	... 5 more

OpenJDK exited with code : 1

**Comment by KabanFriends** [comment]
Oh, that's a very old version of Minecraft..
Sorry, but I generally don't support older version of Minecraft

**Comment by PwRhGaStPY** [comment]
Possible fix? 
https://github.com/terrarium-earth/Ad-Astra/issues/643#issuecomment-2492988005
