### ISSUE TITLE
Error Loading Album Cover

### ISSUE THREAD

**Issue by 3azygam3r04** [KabanFriends/CraftGR#3]
My game has a problem loading the album's cover in.
I'm running Minecraft 1.19 with the 1.3.0 Fabric version of the mod, playing on a server.
Weirdly enough, it loads a certain album cover, which will always stay the same, but it's not the one playing.
See error below.
![image](https://user-images.githubusercontent.com/48602777/191373834-72815e86-f6c4-45ea-998d-b38d6816d339.png)

**Comment by KabanFriends** [comment]
Oh yeah, I can confirm this happens sometimes. I'm not really sure what causes it, but I can make so that when it fails to get album image, it will fallback to a placeholder icon

**Comment by KabanFriends** [comment]
Fixed in 9b0980a5d7acf4b9905e35de1c388308c97aa1e3
