### ISSUE TITLE
Can't set hotkey for mute/unmute

### ISSUE THREAD

**Issue by Zarantyz** [KabanFriends/CraftGR#9]
I don't have the option to change the hotkey for mute/unmute the audio playback. It's not listed at the keybindings.

**Comment by KabanFriends** [comment]
![image](https://github.com/KabanFriends/CraftGR/assets/45000995/d4917dbc-6298-4f76-8ec5-ff71044e7807)
It should be listed in the Options -> Controls -> Key Binds menu under the CraftGR category. If you can't find it there, other mods you are using might be causing some conflicts.

**Comment by dasdwavbc** [comment]
1.20.1 latest version,no other mod,still no hotkey to set mute/unmute

**Comment by KabanFriends** [comment]
I found that keybind was registered incorrectly on NeoForge version of the mod. Should be fixed in the next release.
